### ISSUE TITLE
plugin blocks execution of "process_data_request_task"

### ISSUE THREAD

**Issue by webers-technikum-wien** [trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner#10]
there seems to be an issue with the GDPR implementation of this plugin

ever since a user created a data request on our site (moodle 3.6), the cron job does not finish running any more, since it halts at "Execute adhoc task: tool_dataprivacy\task\process_data_request_task"

first, what blocked it was the coderunenr plugin itself - after I updated it from 1.5 to 1.5.3 it was fine. However, now this qbehaviour plugin blocks the task

**Comment by trampgeek** [comment]
Can you confirm please that you're running the latest version of the behaviour plugin, 1.3.5 (2018080300)? I updated the GDPR code for both plugins around the same time, August last year. If the update fixed the problem with coderunner itself, I would have thought it would be fixed in the behaviour, too. But if you *are* running the latest version I'll look into it of course.

**Comment by trampgeek** [comment]
Ah, I see. Yes, indeed there was a later fix to the GDPR code in CodeRunner - the previous code was PHP version 7 specific. I assume you have an earlier version of PHP?
I've updated this plugin to v1.3.6 and pushed the change to github. Could you pull that version and confirm that it fixes your problem, please? If so, I'll update the Moodle repository too.
Thanks for reporting and sorry about the hassles.

**Comment by webers-technikum-wien** [comment]
hhm, we are actually running php  7.0.30-0+

i already "fixed" it by just deleting the ad_hoc task for "process_data_request_task" out of the db, so right now the cron is running smoothly again. 

i will try to reproduce the error with a new data request, and then see if the new version fixes it. will report back next week.

**Comment by trampgeek** [comment]
The fact you're already running PHP 7 is a slight worry but only slight - there are additional complications relating to the particular version of Moodle you're running. The privacy provider code in the latest version is now the same as in CoderRunner so I'm pretty sure the problem will be fixed. I'll go ahead and push the change to the Moodle repository. If you get another data request and the problem re-occurs (after updating the code) please let me know but otherwise I'm going to assume all is well and close this. Again, thanks for reporting.
