### ISSUE TITLE
Improving question state assignment

### ISSUE THREAD

**Issue by XiRouz** [trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner#16]
Hello, Richard Lobb, thanks for this plugin and for immense work of your team!

Recently, one of our curious student was doing a test with CR questions. After submitting the correct answer for one of them and getting 1.00/1.00 grade for it, he tried other ways to resolve the problem. The last attempt step was graded with state "wrong" and 0.00/1.00 grade. This led to question state "wrong" with grade 1.00/1.00 after finishing his attempt.

I'm not sure this is expected behaviour, could you clarify this, please?

**Comment by trampgeek** [comment]
Hi XiRoux.
Yes, this is standard Moodle behaviour across all question types, not just CodeRunner. If you make multiple submissions to a question, your grade is the maximum over all submissions. This is a life-saver in practice, because with a web interface it's very easy for a typed character to inadvertently alter the answer to a previously submitted question, rather than the one you thought you were currently working on. It also allows students to explore different answers to a question without being penalised by the penalty regime.

**Comment by trampgeek** [comment]
Again, I think this is standard Moodle question behaviour, isn't it? Here's a screen shot of a multichoice question that I answered three times: once wrongly, once correct, then again wrongly. The state is "Incorrect" but the marks are non-zero.

I don't have a problem with this, personally. The state shows the state the question is currently in (namely, incorrect) while the mark shows the best mark that the question ever achieved. I think it would be odd to have an answer that is quite clearly wrong being displayed as "Partially correct". 

I think the confusion is because the Mark shown up by the question number is just a summary. Note that the full explanation/meaning of the mark is given below the question.

![image](https://github.com/trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner/assets/1101142/060b3931-0582-4d48-9070-b8975a0dfb9b)

**Comment by XiRouz** [comment]
I agree with the concept that the last question attempt step is displayed as intended, although I still find the finishing step state evaluation a little bit odd, but now thinking about it..  I recall the states don't affect the final grade for question or quiz, so if this doesn't affect the completion processes, I guess I should leave this problem.

Sorry for bothering you once again, and thank you for your answer!
